modLoader = "javafml"
loaderVersion = "[9,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "platz"
version = "${version}"
displayName = "Platz"
authors = "jusipat"
description = '''
This mod adds interactive town squares to Minecraft.
'''
#logoFile = ""

[[dependencies.platz]]
modId = "neoforge"
type = "required"
versionRange = "[21.7,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.platz]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.7,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.platz]]
modId = "architectury"
type = "required"
versionRange = "[17.0.6,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "platz.mixins.json"
